spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/mrcjx/config-repo
          username: 991516266@qq.com
          password: 991516266@qq.com
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
env:
  test3
label:
  master
girl:
  name: lili
  age: 19